{
  "swagger": "2.0",
  "info" : {
    "description" : "<h1>business-logic Maven Webapp<\/h1>",
    "version" : "0.0.1-SNAPSHOT",
    "title" : "business-logic Maven Webapp"
  },
  "schemes" : [],
  "tags" : [
    {
      "name" : "HelloWorld"
    }
    ,
    {
      "name" : "UserAnalysisResource"
    }
  ],
  "definitions" : {
    "json_Activity" : {
      "type" : "object",
      "title" : "Activity",
          "properties" : {
            "details" : {
"description" : "",
"type" : "object",
"additionalProperties" : {
  "type" : "string"
}
            }
          },
      "example" : {
  "details" : {
    "property1" : "...",
    "property2" : "..."
  }
},
      "description" : ""
    }
    ,
    "json_ActivityHistory" : {
      "type" : "object",
      "title" : "ActivityHistory",
          "properties" : {
            "dailyActivity" : {
"description" : "",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_DailyActivity"
}
            },
            "id" : {
"description" : "",
"type" : "string"
            }
          },
      "example" : {
  "dailyActivity" : [ {
    "date" : 12345,
    "activity" : [ {
      "details" : {
        "property1" : "...",
        "property2" : "..."
      }
    }, {
      "details" : {
        "property1" : "...",
        "property2" : "..."
      }
    } ]
  }, {
    "date" : 12345,
    "activity" : [ {
      "details" : {
        "property1" : "...",
        "property2" : "..."
      }
    }, {
      "details" : {
        "property1" : "...",
        "property2" : "..."
      }
    } ]
  } ],
  "id" : "..."
},
      "description" : ""
    }
    ,
    "json_DailyActivity" : {
      "type" : "object",
      "title" : "DailyActivity",
          "properties" : {
            "date" : {
"description" : "",
"type" : "number"
            },
            "activity" : {
"description" : "",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_Activity"
}
            }
          },
      "example" : {
  "date" : 12345,
  "activity" : [ {
    "details" : {
      "property1" : "...",
      "property2" : "..."
    }
  }, {
    "details" : {
      "property1" : "...",
      "property2" : "..."
    }
  } ]
},
      "description" : ""
    }
    ,
    "json_DailyFood" : {
      "type" : "object",
      "title" : "DailyFood",
          "properties" : {
            "food" : {
"description" : "",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_Food"
}
            },
            "date" : {
"description" : "",
"type" : "number"
            }
          },
      "example" : {
  "food" : [ {
    "unit" : "...",
    "name" : "...",
    "quantity" : 12345,
    "calories" : 12345
  }, {
    "unit" : "...",
    "name" : "...",
    "quantity" : 12345,
    "calories" : 12345
  } ],
  "date" : 12345
},
      "description" : ""
    }
    ,
    "json_Food" : {
      "type" : "object",
      "title" : "Food",
          "properties" : {
            "unit" : {
"description" : "",
"type" : "string"
            },
            "name" : {
"description" : "",
"type" : "string"
            },
            "quantity" : {
"description" : "",
"type" : "number"
            },
            "calories" : {
"description" : "",
"type" : "number"
            }
          },
      "example" : {
  "unit" : "...",
  "name" : "...",
  "quantity" : 12345,
  "calories" : 12345
},
      "description" : ""
    }
    ,
    "json_FoodHistory" : {
      "type" : "object",
      "title" : "FoodHistory",
          "properties" : {
            "id" : {
"description" : "",
"type" : "string"
            },
            "dailyFood" : {
"description" : "",
"type" : "array",
"items" : {
  "$ref" : "#/definitions/json_DailyFood"
}
            }
          },
      "example" : {
  "id" : "...",
  "dailyFood" : [ {
    "food" : [ {
      "unit" : "...",
      "name" : "...",
      "quantity" : 12345,
      "calories" : 12345
    }, {
      "unit" : "...",
      "name" : "...",
      "quantity" : 12345,
      "calories" : 12345
    } ],
    "date" : 12345
  }, {
    "food" : [ {
      "unit" : "...",
      "name" : "...",
      "quantity" : 12345,
      "calories" : 12345
    }, {
      "unit" : "...",
      "name" : "...",
      "quantity" : 12345,
      "calories" : 12345
    } ],
    "date" : 12345
  } ]
},
      "description" : ""
    }
    ,
    "json_HealthData" : {
      "type" : "object",
      "title" : "HealthData",
          "properties" : {
            "bmr" : {
"description" : "",
"type" : "number"
            },
            "dailyKCaloriesGoal" : {
"description" : "",
"type" : "number"
            },
            "pal" : {
"description" : "",
"$ref" : "#/definitions/json_Pal"
            },
            "physicalActivity" : {
"description" : "",
"type" : "boolean"
            },
            "optimalWeight" : {
"description" : "",
"type" : "number"
            },
            "age" : {
"description" : "",
"type" : "number"
            },
            "weight" : {
"description" : "",
"type" : "number"
            },
            "height" : {
"description" : "",
"type" : "number"
            },
            "bmi" : {
"description" : "",
"type" : "number"
            },
            "sex" : {
"description" : "",
"type" : "boolean"
            }
          },
      "example" : {
  "bmr" : 12345.0,
  "dailyKCaloriesGoal" : 12345,
  "pal" : "HEAVY",
  "physicalActivity" : true,
  "optimalWeight" : 12345.0,
  "age" : 12345,
  "weight" : 12345.0,
  "height" : 12345.0,
  "bmi" : 12345.0,
  "sex" : true
},
      "description" : ""
    }
    ,
    "json_Pal" : {
      "type" : "string",
      "title" : "Pal",
          "enum" : [
            "LIGHT",
            "MODERATE",
            "HEAVY"
          ],
      "description" : ""
    }
    ,
    "json_Statistics" : {
      "type" : "object",
      "title" : "Statistics",
          "properties" : {
            "spent" : {
"description" : "",
"type" : "number"
            },
            "introduced" : {
"description" : "",
"type" : "number"
            },
            "difference" : {
"description" : "",
"type" : "number"
            }
          },
      "example" : {
  "spent" : 12345,
  "introduced" : 12345,
  "difference" : 12345
},
      "description" : ""
    }
    ,
    "json_User" : {
      "type" : "object",
      "title" : "User",
          "properties" : {
            "username" : {
"description" : "",
"type" : "string"
            },
            "password" : {
"description" : "",
"type" : "string"
            },
            "foodHistory" : {
"description" : "",
"$ref" : "#/definitions/json_FoodHistory"
            },
            "id" : {
"description" : "",
"type" : "string"
            },
            "healthData" : {
"description" : "",
"$ref" : "#/definitions/json_HealthData"
            },
            "activityHistory" : {
"description" : "",
"$ref" : "#/definitions/json_ActivityHistory"
            }
          },
      "example" : {
  "username" : "...",
  "password" : "...",
  "foodHistory" : {
    "id" : "...",
    "dailyFood" : [ {
      "food" : [ { }, { } ],
      "date" : 12345
    }, {
      "food" : [ { }, { } ],
      "date" : 12345
    } ]
  },
  "id" : "...",
  "healthData" : {
    "bmr" : 12345.0,
    "dailyKCaloriesGoal" : 12345,
    "pal" : "LIGHT",
    "physicalActivity" : true,
    "optimalWeight" : 12345.0,
    "age" : 12345,
    "weight" : 12345.0,
    "height" : 12345.0,
    "bmi" : 12345.0,
    "sex" : true
  },
  "activityHistory" : {
    "dailyActivity" : [ {
      "date" : 12345,
      "activity" : [ { }, { } ]
    }, {
      "date" : 12345,
      "activity" : [ { }, { } ]
    } ],
    "id" : "..."
  }
},
      "description" : ""
    }
    ,
    "xml_ns0_activity" : {
      "type" : "object",
      "title" : "activity",
      "allOf" : [
        {
          "properties" : {
            "details" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "object"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_activityHistory" : {
      "type" : "object",
      "title" : "activityHistory",
      "allOf" : [
        {
          "properties" : {
            "dailyActivity" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_dailyActivity"
            },
            "id" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "string"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_dailyActivity" : {
      "type" : "object",
      "title" : "dailyActivity",
      "allOf" : [
        {
          "properties" : {
            "activity" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_activity"
            },
            "date" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_dailyFood" : {
      "type" : "object",
      "title" : "dailyFood",
      "allOf" : [
        {
          "properties" : {
            "date" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "food" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_food"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_food" : {
      "type" : "object",
      "title" : "food",
      "allOf" : [
        {
          "properties" : {
            "calories" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "name" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "string"
            },
            "quantity" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "unit" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "string"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_foodHistory" : {
      "type" : "object",
      "title" : "foodHistory",
      "allOf" : [
        {
          "properties" : {
            "dailyFood" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_dailyFood"
            },
            "id" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "string"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_healthData" : {
      "type" : "object",
      "title" : "healthData",
      "allOf" : [
        {
          "properties" : {
            "age" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "bmi" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "bmr" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "dailyKCaloriesGoal" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "height" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "optimalWeight" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "pal" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_pal"
            },
            "physicalActivity" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "boolean"
            },
            "sex" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "boolean"
            },
            "weight" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_pal" : {
      "type" : "string",
      "title" : "pal",
          "enum" : [
            "LIGHT",
            "MODERATE",
            "HEAVY"
          ],
      "description" : ""
    }
    ,
    "xml_ns0_statistics" : {
      "type" : "object",
      "title" : "statistics",
      "allOf" : [
        {
          "properties" : {
            "difference" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "introduced" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            },
            "spent" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "number"
            }
          }
        }
      ],
      "description" : ""
    }
    ,
    "xml_ns0_user" : {
      "type" : "object",
      "title" : "user",
      "allOf" : [
        {
          "properties" : {
            "activityHistory" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_activityHistory"
            },
            "foodHistory" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_foodHistory"
            },
            "healthData" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_healthData"
            },
            "id" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "string"
            },
            "password" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "string"
            },
            "username" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"type" : "string"
            }
          }
        }
      ],
      "description" : ""
    }
  },
  "paths": {
    "\/hello-world" : {
      "get" : {
        "tags" : [ "HelloWorld" ],
        "summary" : "GET REQUESTS.",
        "description" : "GET REQUESTS",
        "operationId" : "resource_HelloWorld_helloWorld_GET",
        "produces" : [ "application/json" ],
        "parameters" : [
        ],
        "responses" : {
          "200" : {
            "schema" : {
"description" : "",
"type" : "file"
            },
            "examples" : {
            },
            "description" : ""
          }
        }
      }
    }
    ,
    "\/user/health-data" : {
      "post" : {
        "tags" : [ "UserAnalysisResource" ],
        "description" : "",
        "operationId" : "resource_UserAnalysisResource_computeUserHealthData_POST",
        "consumes" : [ "application/xml", "application/json", "text/xml" ],
        "produces" : [ "application/xml", "application/json", "text/xml" ],
        "parameters" : [
          {
            "name" : "body",
            "in" : "body",
            "schema" : {
"description" : "",
"$ref" : "#/definitions/json_User"
            },
            "description" : ""
          }
        ],
        "responses" : {
          "201" : {
            "schema" : {
"description" : "",
"$ref" : "#/definitions/json_User"
            },
            "examples" : {
              "application/json" : {
  "username" : "...",
  "password" : "...",
  "foodHistory" : {
    "id" : "...",
    "dailyFood" : [ {
      "food" : [ { }, { } ],
      "date" : 12345
    }, {
      "food" : [ { }, { } ],
      "date" : 12345
    } ]
  },
  "id" : "...",
  "healthData" : {
    "bmr" : 12345.0,
    "dailyKCaloriesGoal" : 12345,
    "pal" : "LIGHT",
    "physicalActivity" : true,
    "optimalWeight" : 12345.0,
    "age" : 12345,
    "weight" : 12345.0,
    "height" : 12345.0,
    "bmi" : 12345.0,
    "sex" : true
  },
  "activityHistory" : {
    "dailyActivity" : [ {
      "date" : 12345,
      "activity" : [ { }, { } ]
    }, {
      "date" : 12345,
      "activity" : [ { }, { } ]
    } ],
    "id" : "..."
  }
}
            },
            "description" : ""
          }
        }
      }
    }
    ,
    "\/user/{userId}/calories-count" : {
      "get" : {
        "tags" : [ "UserAnalysisResource" ],
        "summary" : "GET REQUESTS.",
        "description" : "GET REQUESTS",
        "operationId" : "resource_UserAnalysisResource_computeCaloriesCountFromDates_GET",
        "produces" : [ "application/xml", "application/json", "text/xml" ],
        "parameters" : [
          {
            "name" : "userId",
            "in" : "path",
            "required" : true,
            "type" : "string",
            "description" : ""
          },
          {
            "name" : "from",
            "in" : "query",
            "default" : "-1",
            "type" : "integer",
            "description" : ""
          },
          {
            "name" : "to",
            "in" : "query",
            "default" : "-1",
            "type" : "integer",
            "description" : ""
          }
        ],
        "responses" : {
          "200" : {
            "schema" : {
"description" : "",
"$ref" : "#/definitions/json_Statistics"
            },
            "examples" : {
              "application/json" : {
  "spent" : 12345,
  "introduced" : 12345,
  "difference" : 12345
}
            },
            "description" : ""
          }
        }
      }
    }
  }
}
